import type { PanelCategory } from '@/types';

export interface PanelRegistryEntry {
  id: string;
  name: string;
  category: PanelCategory;
  defaultW: number;
  defaultH: number;
  minW: number;
  minH: number;
  resizable: boolean;
  noHeader?: boolean;     // full-width bars don't need panel chrome
  uiComponent?: boolean;  // UI-only (separators) — noHeader but NOT stretched to full-width
  adminOnly?: boolean;    // hidden from non-admin panel pickers (future use)
  refreshInterval: number;
  dataSources: string[];
  description: string;
  icon: string;
}

export const PANEL_REGISTRY: PanelRegistryEntry[] = [
  // ── Bitcoin Core ──
  {
    id: 'btc-hero',
    name: 'Bitcoin — 24hr',
    category: 'bitcoin',
    defaultW: 260, defaultH: 120, minW: 200, minH: 100,
    resizable: false,
    refreshInterval: 60,
    dataSources: ['btcMarket'],
    description: 'Current BTC price with 24-hour change',
    icon: 'bitcoin',
  },
  {
    id: 'btc-market',
    name: 'Bitcoin — Market',
    category: 'bitcoin',
    defaultW: 260, defaultH: 260, minW: 200, minH: 200,
    resizable: false,
    refreshInterval: 60,
    dataSources: ['btcMarket'],
    description: '7d/30d change, market cap, volume, supply, ATH',
    icon: 'chart',
  },
  {
    id: 'btc-network',
    name: 'Bitcoin — Network',
    category: 'bitcoin',
    defaultW: 260, defaultH: 280, minW: 200, minH: 200,
    resizable: false,
    refreshInterval: 60,
    dataSources: ['btcNetwork'],
    description: 'Block height, fees, mempool, hashrate, difficulty, halving',
    icon: 'network',
  },
  {
    id: 'btc-mining',
    name: 'Bitcoin — Mining',
    category: 'bitcoin',
    defaultW: 264, defaultH: 220, minW: 220, minH: 176,
    resizable: false,
    refreshInterval: 60,
    dataSources: ['btcNetwork'],
    description: 'Block reward, blocks today, revenue, epoch, retarget',
    icon: 'mining',
  },
  {
    id: 'lightning',
    name: 'Lightning Network',
    category: 'bitcoin',
    defaultW: 260, defaultH: 180, minW: 200, minH: 140,
    resizable: false,
    refreshInterval: 60,
    dataSources: ['lightning'],
    description: 'Channels, capacity, nodes, fees',
    icon: 'lightning',
  },
  {
    id: 'conviction',
    name: 'Conviction Score',
    category: 'bitcoin',
    defaultW: 264, defaultH: 176, minW: 220, minH: 132,
    resizable: true,
    refreshInterval: 60,
    dataSources: ['convictionScore'],
    description: '5-signal weighted conviction gauge with interactive breakdown',
    icon: 'conviction',
  },
  {
    id: 'btc-charts',
    name: 'Bitcoin Charts',
    category: 'bitcoin',
    defaultW: 660, defaultH: 396, minW: 440, minH: 308,
    resizable: true,
    refreshInterval: 300,
    dataSources: ['charts'],
    description: '30-day price, hashrate, MVRV, exchange balance charts',
    icon: 'chart',
  },

  // ── On-Chain ──
  {
    id: 'onchain-sentiment',
    name: 'On-Chain Sentiment',
    category: 'onchain',
    defaultW: 260, defaultH: 280, minW: 200, minH: 200,
    resizable: false,
    refreshInterval: 900,
    dataSources: ['onchainFlows', 'onchainMvrv'],
    description: 'MVRV, exchange flows, net flow, interpretation',
    icon: 'onchain',
  },
  {
    id: 'whale-txs',
    name: 'Whale Transactions',
    category: 'onchain',
    defaultW: 264, defaultH: 264, minW: 220, minH: 176,
    resizable: true,
    refreshInterval: 120,
    dataSources: ['whales'],
    description: 'Large BTC transactions (>100 BTC)',
    icon: 'whale',
  },

  {
    id: 'utxo-age-dist',
    name: 'UTXO Age Distribution',
    category: 'onchain',
    defaultW: 792, defaultH: 352, minW: 528, minH: 220,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: '90-day stacked bar chart of Bitcoin supply by coin age — 10 bands from <1d to 5yr+',
    icon: 'onchain',
  },
  {
    id: 'lth-sth-supply',
    name: 'LTH / STH Supply',
    category: 'onchain',
    defaultW: 792, defaultH: 440, minW: 528, minH: 308,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: '1yr dual-area chart of Long-Term vs Short-Term Holder supply + LTH% regime line (155-day threshold)',
    icon: 'onchain',
  },
  {
    id: 'urpd',
    name: 'Supply at Cost Basis (URPD)',
    category: 'onchain',
    defaultW: 528, defaultH: 440, minW: 352, minH: 308,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: 'UTXO Realised Price Distribution — horizontal bar chart of BTC supply by cost basis with profit/loss zones',
    icon: 'onchain',
  },
  {
    id: 'cdd',
    name: 'Value of Coin Days Destroyed',
    category: 'onchain',
    defaultW: 792, defaultH: 352, minW: 528, minH: 220,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: '90-day VOCDD bar chart (hot/cold vs 30D MA) with signal banner — CDD × USD price at time of spend',
    icon: 'onchain',
  },

  // ── Macro ──
  {
    id: 'market-indices',
    name: 'Market Indices — 24hr',
    category: 'macro',
    defaultW: 260, defaultH: 300, minW: 200, minH: 200,
    resizable: false,
    refreshInterval: 1800,
    dataSources: ['indices'],
    description: 'S&P 500, NASDAQ, DJI, FTSE, DAX, Nikkei, HSI, VIX',
    icon: 'indices',
  },
  {
    id: 'commodities',
    name: 'Commodities — 24hr',
    category: 'macro',
    defaultW: 260, defaultH: 300, minW: 200, minH: 200,
    resizable: false,
    refreshInterval: 1800,
    dataSources: ['commodities'],
    description: 'Gold, Silver, Oil, NatGas, Copper, DXY, US10Y, US2Y',
    icon: 'commodities',
  },
  {
    id: 'fx-macro',
    name: 'FX & Macro — 24hr',
    category: 'macro',
    defaultW: 260, defaultH: 200, minW: 200, minH: 140,
    resizable: false,
    refreshInterval: 1800,
    dataSources: ['fx'],
    description: 'EUR/USD, GBP/USD, USD/JPY, USD/CNY',
    icon: 'fx',
  },
  {
    id: 'central-bank',
    name: 'Central Bank Watch',
    category: 'macro',
    defaultW: 260, defaultH: 200, minW: 200, minH: 140,
    resizable: false,
    refreshInterval: 21600,
    dataSources: ['rates'],
    description: 'Fed, ECB, BOJ, BOE policy rates and next decisions',
    icon: 'bank',
  },

  // ── Geopolitical ──
  {
    id: 'globe',
    name: 'Global Situation Map',
    category: 'geopolitical',
    defaultW: 528, defaultH: 396, minW: 352, minH: 264,
    resizable: true,
    refreshInterval: 300,
    dataSources: ['news'],
    description: 'Interactive globe with filtered event markers and country overlays',
    icon: 'globe',
  },
  {
    id: 'intel-feed',
    name: 'Intelligence Briefing',
    category: 'geopolitical',
    defaultW: 528, defaultH: 352, minW: 352, minH: 220,
    resizable: true,
    refreshInterval: 300,
    dataSources: ['news'],
    description: 'Category-filtered RSS intelligence feed (18 sources)',
    icon: 'briefing',
  },
  {
    id: 'ai-briefing',
    name: 'AI Intelligence',
    category: 'geopolitical',
    defaultW: 528, defaultH: 352, minW: 352, minH: 220,
    resizable: true,
    refreshInterval: 60,
    dataSources: ['briefing'],
    description: 'Grok multi-agent synthesis briefing',
    icon: 'ai',
  },
  {
    id: 'fear-greed',
    name: 'Fear & Greed Index',
    category: 'bitcoin',
    defaultW: 260, defaultH: 160, minW: 200, minH: 120,
    resizable: false,
    refreshInterval: 3600,
    dataSources: ['fearGreed'],
    description: 'Current Fear & Greed reading with 7-day trend',
    icon: 'sentiment',
  },

  {
    id: 'cb-asset-chart',
    name: 'Central Bank Balance Sheets',
    category: 'macro',
    defaultW: 528, defaultH: 660, minW: 440, minH: 484,
    resizable: true,
    refreshInterval: 604800,
    dataSources: ['cbAssets'],
    description: 'Donut composition + 10-year timeline for Fed, ECB, BOJ, BOE, PBoC balance sheets',
    icon: 'chart',
  },
  {
    id: 'cb-rates-chart',
    name: 'Central Bank Rates',
    category: 'macro',
    defaultW: 660, defaultH: 396, minW: 440, minH: 264,
    resizable: true,
    refreshInterval: 604800, // 7 days
    dataSources: ['cbRates'],
    description: '10-year Fed, ECB, BOE, BOJ policy rate chart — the 2022 hiking cycle in context',
    icon: 'chart',
  },
  {
    id: 'inflation-chart',
    name: 'Inflation Monitor',
    category: 'macro',
    defaultW: 660, defaultH: 396, minW: 440, minH: 264,
    resizable: true,
    refreshInterval: 604800, // 7 days — monthly statistic
    dataSources: ['inflation'],
    description: 'G7 vs extreme inflation — multi-line CPI chart with log scale toggle',
    icon: 'chart',
  },

  {
    id: 'hash-ribbon',
    name: 'Hash Ribbon',
    category: 'onchain',
    defaultW: 660, defaultH: 352, minW: 440, minH: 264,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: '90-day hash rate ribbon (30d/60d MA) — miner capitulation recovery signal',
    icon: 'onchain',
  },
  {
    id: 'puell-multiple',
    name: 'Puell Multiple',
    category: 'onchain',
    defaultW: 660, defaultH: 352, minW: 440, minH: 264,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: 'Daily miner revenue vs 365-day MA — macro cycle undervalue/overvalue indicator',
    icon: 'onchain',
  },
  {
    id: 'network-signals',
    name: 'SOPR & Active Addresses',
    category: 'onchain',
    defaultW: 528, defaultH: 528, minW: 440, minH: 396,
    resizable: true,
    refreshInterval: 3600,
    dataSources: ['brk'],
    description: 'SOPR (profit/loss on-chain spending) + active address trend — 60-day dual chart',
    icon: 'onchain',
  },

  {
    id: 'onchain-analysis',
    name: 'On-Chain Deep Analysis',
    category: 'onchain',
    defaultW: 704, defaultH: 528, minW: 440, minH: 352,
    resizable: true,
    refreshInterval: 21600, // 6 hours
    dataSources: ['brk', 'briefing'],
    description: 'VIP Grok-3 deep dive — market regime, miner health, holder behaviour, price outlook',
    icon: 'ai',
  },

  // ── AI Analysis ──
  {
    id: 'signal-interpreter',
    name: 'Signal Synthesis',
    category: 'ai',
    defaultW: 748, defaultH: 396, minW: 528, minH: 264,
    resizable: true,
    refreshInterval: 43200,
    dataSources: ['briefing'],
    description: 'AI synthesis of current signals — auto-detects live market, on-chain, and macro readings',
    icon: 'ai',
  },
  {
    id: 'cohort-analysis',
    name: 'Cohort Analysis',
    category: 'ai',
    defaultW: 748, defaultH: 352, minW: 528, minH: 220,
    resizable: true,
    refreshInterval: 21600,
    dataSources: ['briefing'],
    description: 'Dominant Bitcoin cohort, implication, and confidence — LTH/STH/whale/retail breakdown',
    icon: 'ai',
  },
  {
    id: 'bitcoin-argument',
    name: 'Bitcoin Argument',
    category: 'ai',
    defaultW: 748, defaultH: 396, minW: 440, minH: 264,
    resizable: true,
    refreshInterval: 43200,
    dataSources: ['briefing'],
    description: 'AI-generated 3-point case for Bitcoin based on current macro and network data',
    icon: 'ai',
  },

  // ── UI Components ──
  {
    id: 'h-separator',
    name: 'Horizontal Separator',
    category: 'ui',
    defaultW: 264, defaultH: 44, minW: 88, minH: 44,
    resizable: true,
    noHeader: true,
    uiComponent: true,
    refreshInterval: 0,
    dataSources: [],
    description: 'Horizontal rule — drag to position, resize to span columns',
    icon: 'separator',
  },
  {
    id: 'v-separator',
    name: 'Vertical Separator',
    category: 'ui',
    defaultW: 44, defaultH: 264, minW: 44, minH: 88,
    resizable: true,
    noHeader: true,
    uiComponent: true,
    refreshInterval: 0,
    dataSources: [],
    description: 'Vertical rule — drag to position, resize to span rows',
    icon: 'separator',
  },

  // ── Full-width bars ──
  {
    id: 'wire',
    name: 'Wire',
    category: 'geopolitical',
    defaultW: 1140, defaultH: 44, minW: 440, minH: 44,
    resizable: true,
    noHeader: true,
    refreshInterval: 300,
    dataSources: ['news'],
    description: 'Scrolling news ticker — top headlines from 17 RSS sources',
    icon: 'wire',
  },
  {
    id: 'tikr',
    name: 'Tikr',
    category: 'bitcoin',
    defaultW: 1140, defaultH: 44, minW: 440, minH: 44,
    resizable: true,
    noHeader: true,
    refreshInterval: 60,
    dataSources: ['btcEquities'],
    description: 'BTC equities ticker — ETFs, miners, and proxy stocks',
    icon: 'tikr',
  },
  {
    id: 'economic-events',
    name: 'Upcoming',
    category: 'macro',
    defaultW: 1140, defaultH: 44, minW: 440, minH: 44,
    resizable: true,
    noHeader: true,
    refreshInterval: 3600,
    dataSources: ['events'],
    description: 'Upcoming economic events — FOMC, CPI, central bank decisions',
    icon: 'calendar',
  },
  {
    id: 'macro-analysis',
    name: 'Macro Deep Analysis',
    category: 'macro',
    defaultW: 792, defaultH: 440, minW: 440, minH: 352,
    resizable: true,
    refreshInterval: 21600, // 6 hours
    dataSources: ['briefing'],
    description: 'VIP Grok-3 deep dive — monetary policy, liquidity, risk appetite, dollar, inflation, Bitcoin outlook',
    icon: 'ai',
  },
  {
    id: 'm2-chart',
    name: 'M2 Money Supply',
    category: 'macro',
    defaultW: 660, defaultH: 420, minW: 420, minH: 280,
    resizable: true,
    refreshInterval: 604800, // 7 days
    dataSources: ['fred'],
    description: 'G4 M2 money supply indexed to 100 — USA, EU, UK, Japan',
    icon: 'chart',
  },
];

export function getPanelById(id: string): PanelRegistryEntry | undefined {
  // Direct match first
  const direct = PANEL_REGISTRY.find((p) => p.id === id);
  if (direct) return direct;
  // UI components use unique instance IDs (e.g. "h-separator-1712345678") — resolve by prefix
  return PANEL_REGISTRY.find((p) => p.uiComponent && id.startsWith(p.id + '-'));
}
