/**
 * GET /api/ai/cycle-historian
 *
 * Returns stored weekly Cycle Position historical analogues (last 13 weeks).
 * Data is pre-generated by the weekly cron at /api/cron/cycle-historian.
 *
 * Auth required. No tier gate — pre-generated data has no per-user AI cost.
 */

import { NextResponse } from 'next/server';
import { getSession }   from '@/lib/auth/session';
import { prisma }       from '@/lib/db';

export const dynamic = 'force-dynamic';

export interface CycleHistorianAnnotation {
  // Snapshot at generation time
  composite:          number;
  phase:              string;
  btcPrice:           number;
  mvrv:               number | null;
  puell:              number | null;
  piCycleRatio:       number | null;
  rainbowBand:        number | null;
  realisedPriceRatio: number | null;
  // Grok analysis
  historicalContext:  string;
  priceChange90d:     string;
  priceChange180d:    string;
  priceChange365d:    string;
  caveats:            string;
  // Metadata
  weekKey:     string;
  generatedAt: string;
}

export async function GET() {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const rows = await (prisma as any).signalAnnotation.findMany({
      where:   { panelId: 'cycle-historian' },
      orderBy: { generatedAt: 'desc' },
      take:    13,
    });

    const weeks: CycleHistorianAnnotation[] = rows
      .map((row: { annotation: string }) => {
        try {
          return JSON.parse(row.annotation) as CycleHistorianAnnotation;
        } catch {
          return null;
        }
      })
      .filter(Boolean);

    return NextResponse.json({ weeks });
  } catch (err) {
    console.error('[CycleHistorian GET] DB error:', err);
    return NextResponse.json({ weeks: [] });
  }
}
