/**
 * Geographic reference detection for RSS headlines.
 * Returns a readable country/region name, or null if no match.
 *
 * Used to populate ClassifiedArticle.geoReference, which globe marker
 * logic can use as an input (existing lat/lon logic in rss.ts unchanged).
 */

// [searchTerm, displayName] — order matters: more specific first
const GEO_TERMS: [string, string][] = [
  // ── Middle East / conflict zone ──────────────────────────────────────
  ['strait of hormuz', 'Strait of Hormuz'],
  ['north korea',      'North Korea'],
  ['south korea',      'South Korea'],
  ['saudi arabia',     'Saudi Arabia'],
  ['west bank',        'West Bank'],
  ['hong kong',        'Hong Kong'],
  ['south africa',     'South Africa'],
  ['united states',    'United States'],
  ['united kingdom',   'United Kingdom'],
  ['new zealand',      'New Zealand'],

  // Single-word / short — placed after multi-word to avoid false matches
  ['palestinian',  'Gaza / Palestine'],
  ['palestine',    'Gaza / Palestine'],
  ['hezbollah',    'Lebanon'],
  ['houthi',       'Yemen'],
  ['hamas',        'Gaza'],
  ['gaza',         'Gaza'],
  ['pyongyang',    'North Korea'],
  ['taipei',       'Taiwan'],
  ['taiwan',       'Taiwan'],
  ['iranian',      'Iran'],
  ['tehran',       'Iran'],
  ['iran',         'Iran'],
  ['israeli',      'Israel'],
  ['jerusalem',    'Israel'],
  ['tel aviv',     'Israel'],
  ['israel',       'Israel'],
  ['ukrainian',    'Ukraine'],
  ['kyiv',         'Ukraine'],
  ['ukraine',      'Ukraine'],
  ['russian',      'Russia'],
  ['kremlin',      'Russia'],
  ['moscow',       'Russia'],
  ['russia',       'Russia'],
  ['chinese',      'China'],
  ['beijing',      'China'],
  ['shanghai',     'China'],
  ['china',        'China'],
  ['baghdad',      'Iraq'],
  ['iraq',         'Iraq'],
  ['damascus',     'Syria'],
  ['syria',        'Syria'],
  ['beirut',       'Lebanon'],
  ['lebanon',      'Lebanon'],
  ['riyadh',       'Saudi Arabia'],
  ['saudi',        'Saudi Arabia'],
  ['sanaa',        'Yemen'],
  ['yemen',        'Yemen'],
  ['kabul',        'Afghanistan'],
  ['pakistan',     'Pakistan'],
  ['modi',         'India'],
  ['india',        'India'],
  ['turkish',      'Turkey'],
  ['ankara',       'Turkey'],
  ['istanbul',     'Turkey'],
  ['turkey',       'Turkey'],
  ['german',       'Germany'],
  ['berlin',       'Germany'],
  ['germany',      'Germany'],
  ['french',       'France'],
  ['macron',       'France'],
  ['paris',        'France'],
  ['france',       'France'],
  ['starmer',      'United Kingdom'],
  ['britain',      'United Kingdom'],
  ['british',      'United Kingdom'],
  ['london',       'United Kingdom'],
  ['washington',   'United States'],
  ['pentagon',     'United States'],
  ['congress',     'United States'],
  ['trump',        'United States'],
  ['biden',        'United States'],
  ['american',     'United States'],
  ['zelensky',     'Ukraine'],
  ['netanyahu',    'Israel'],
  ['putin',        'Russia'],
  ['xi jinping',   'China'],
  ['canada',       'Canada'],
  ['ottawa',       'Canada'],
  ['toronto',      'Canada'],
  ['japan',        'Japan'],
  ['tokyo',        'Japan'],
  ['seoul',        'South Korea'],
  ['brazil',       'Brazil'],
  ['sao paulo',    'Brazil'],
  ['argentina',    'Argentina'],
  ['buenos aires', 'Argentina'],
  ['milei',        'Argentina'],
  ['mexico',       'Mexico'],
  ['nigeria',      'Nigeria'],
  ['lagos',        'Nigeria'],
  ['cairo',        'Egypt'],
  ['egypt',        'Egypt'],
  ['sudan',        'Sudan'],
  ['ethiopia',     'Ethiopia'],
  ['australia',    'Australia'],
  ['sydney',       'Australia'],
  ['nato',         'NATO'],
  ['european',     'Europe'],
  ['europe',       'Europe'],
  ['brussels',     'Europe'],
  ['gulf',         'Gulf Region'],
  ['opec',         'Gulf Region'],
];

export function detectGeoReference(headline: string): string | null {
  const lower = headline.toLowerCase();
  for (const [term, name] of GEO_TERMS) {
    if (lower.includes(term)) return name;
  }
  return null;
}
